class_name FlowerAssets
extends RefCounted

## Hand-drawn flower art: res://assets/sprites/flowers/<type_id>_t<tier>.svg
## (generated by scripts/art/flowers_gen.py). Types without a file keep the
## procedural CampPlantDraw fallback.

const DIR := "res://assets/sprites/flowers/"

## Misses are cached too — draw_plant runs every frame in Arena/Camp.
static var _cache: Dictionary = {}


static func get_texture(type_id: String, tier: int) -> Texture2D:
	var key := "%s_t%d" % [type_id, tier]
	if _cache.has(key):
		return _cache[key]
	var tex: Texture2D = null
	var path := DIR + key + ".svg"
	if ResourceLoader.exists(path):
		tex = load(path) as Texture2D
	_cache[key] = tex
	return tex
